### ISSUE TITLE
Feedback Iteração 0

### ISSUE THREAD

**Issue by pedrojsn96** [IF977/SeraQChoveu#1]
Fala pessoal.

Passando para dar o feedback da iteração0 de vocês.

**HU**: 10 - 1 = 9(Descrição das HU'S)
A HU tem que ta relacionado com o objetivo do projeto de vocês. Pelo o que entendi a razão de vocês existirem é para **informar sobre dados estatísticos relacionados a ocorrência de chuvas em determinados locais/intervalos** e não sobre "planejar melhor uma viagem".
OBS: O cliente só que saber se um local chove apenas pra planejar uma viagem? E se ele quiser se prevenir contra algum incidente devido a ocorrência de chuvas? 
Segue:
- Como usuário (logado)/Gostaria de escolher a data da viagem/Para definir período a ser pesquisado pelo aplicativo
- Como usuário (logado)/Gostaria de ter informações sobre a cidade e período escolhidos/Para planejar melhor uma viagem

**Ata de reunião** : 10
**Mockups e Storyboards** : 5+5 = 10
OBS: Na Storyboards melhorá torná menos confuso o modo como vocês estão apresentando o relacionamento entre as telas. 
**Preenchimento do github** : 10 - 4 = 6 . O uso de Issue, tags e milestone é obrigatório.  
**Postmortem** : 10

OBS: Lembre sempre de distribuir bem as atividades entre os membros. 

**_Em caso de dúvida, nos comunicamos via Slack._**

**Comment by svaf2** [comment]
Pedro, agradecemos o feedback! Quanto as HU's, o objetivo é focado realmente no planejamento de viagens a longo prazo dado que já existem dados de previsão do tempo semanais. Um usuário que deseja se prevenir contra algum incidente dificilmente utilizaria nossa ferramenta por já existirem outras de fácil acesso (Google Now por exemplo).
