### ISSUE TITLE
Verificação nos testes (Cucumber)

### ISSUE THREAD

**Issue by rafjordao** [IF977/SeraQChoveu#21]
Oi pessoal, o problema está no seguinte passo:

``` ruby
Given (/^[Eu]*estou na página inicial $/) do |root_path|
	visit root_path
end
```
Quando a seguinte linha é executada

``` cucumber
Given Estou na página inicial
```

O cucumber não consegue encontrar o passo, por conta da diferença entre ``Estou`` e ``estou``, além disso, o ``[Eu]*`` no .rb não funcionará como querem, adicionem um espaço em branco depois do ``Eu`` (desta forma ``[Eu ]*``) para que assim ele consiga dar "match" em "Eu estou".

Por ele pular o primeiro passo por não haver mapeamento, ele pula os restantes visto que um dos passos do teste está comprometido.

**Comment by svaf2** [comment]
Muito obrigado Rafael, esse detalhe salvou!
